$(document).ready(function(){
    $('header').hover(function(){
        $('.logo1').hide();
        $('.logo2').css({'display':'block'});
    },function(){
        $('.logo1').show();
        $('.logo2').hide();
    });
});